# -*- coding: utf-8 -*-
############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

from __future__ import print_function
# the following is a hack to get the baseclient to import whether we're in a
# package or not. This makes pep8 unhappy hence the annotations.
try:
    # baseclient and this client are in a package
    from .baseclient import BaseClient as _BaseClient  # @UnusedImport
except:
    # no they aren't
    from baseclient import BaseClient as _BaseClient  # @Reimport


class kb_blast(object):

    def __init__(
            self, url=None, timeout=30 * 60, user_id=None,
            password=None, token=None, ignore_authrc=False,
            trust_all_ssl_certificates=False,
            auth_svc='https://kbase.us/services/authorization/Sessions/Login'):
        if url is None:
            raise ValueError('A url is required')
        self._service_ver = None
        self._client = _BaseClient(
            url, timeout=timeout, user_id=user_id, password=password,
            token=token, ignore_authrc=ignore_authrc,
            trust_all_ssl_certificates=trust_all_ssl_certificates,
            auth_svc=auth_svc)

    def BLASTn_Search(self, params, context=None):
        """
        Methods for BLAST of various flavors of one sequence against many sequences 
        **
        **    overloading as follows:
        **        input_one_type: SequenceSet, Feature, FeatureSet
        **        input_many_type: SequenceSet, SingleEndLibrary, FeatureSet, Genome, GenomeSet
        **        output_type: SequenceSet (if input_many is SS), SingleEndLibrary (if input_many is SELib), (else) FeatureSet
        :param params: instance of type "BLAST_Params" (BLAST Input Params)
           -> structure: parameter "workspace_name" of type "workspace_name"
           (** The workspace object refs are of form: ** **    objects =
           ws.get_objects([{'ref':
           params['workspace_id']+'/'+params['obj_name']}]) ** ** "ref" means
           the entire name combining the workspace id and the object name **
           "id" is a numerical identifier of the workspace or object, and
           should just be used for workspace ** "name" is a string identifier
           of a workspace or object.  This is received from Narrative.),
           parameter "input_one_sequence" of type "sequence", parameter
           "input_one_name" of type "data_obj_name", parameter
           "input_many_name" of type "data_obj_name", parameter
           "input_msa_name" of type "data_obj_name", parameter
           "output_one_name" of type "data_obj_name", parameter
           "output_filtered_name" of type "data_obj_name", parameter
           "ident_thresh" of Double, parameter "e_value" of Double, parameter
           "bitscore" of Double, parameter "overlap_fraction" of Double,
           parameter "maxaccepts" of Double, parameter "rounds" of Double
        :returns: instance of type "BLAST_Output" (BLAST Output) ->
           structure: parameter "report_name" of type "data_obj_name",
           parameter "report_ref" of type "data_obj_ref"
        """
        return self._client.call_method(
            'kb_blast.BLASTn_Search',
            [params], self._service_ver, context)

    def BLASTp_Search(self, params, context=None):
        """
        :param params: instance of type "BLAST_Params" (BLAST Input Params)
           -> structure: parameter "workspace_name" of type "workspace_name"
           (** The workspace object refs are of form: ** **    objects =
           ws.get_objects([{'ref':
           params['workspace_id']+'/'+params['obj_name']}]) ** ** "ref" means
           the entire name combining the workspace id and the object name **
           "id" is a numerical identifier of the workspace or object, and
           should just be used for workspace ** "name" is a string identifier
           of a workspace or object.  This is received from Narrative.),
           parameter "input_one_sequence" of type "sequence", parameter
           "input_one_name" of type "data_obj_name", parameter
           "input_many_name" of type "data_obj_name", parameter
           "input_msa_name" of type "data_obj_name", parameter
           "output_one_name" of type "data_obj_name", parameter
           "output_filtered_name" of type "data_obj_name", parameter
           "ident_thresh" of Double, parameter "e_value" of Double, parameter
           "bitscore" of Double, parameter "overlap_fraction" of Double,
           parameter "maxaccepts" of Double, parameter "rounds" of Double
        :returns: instance of type "BLAST_Output" (BLAST Output) ->
           structure: parameter "report_name" of type "data_obj_name",
           parameter "report_ref" of type "data_obj_ref"
        """
        return self._client.call_method(
            'kb_blast.BLASTp_Search',
            [params], self._service_ver, context)

    def BLASTx_Search(self, params, context=None):
        """
        :param params: instance of type "BLAST_Params" (BLAST Input Params)
           -> structure: parameter "workspace_name" of type "workspace_name"
           (** The workspace object refs are of form: ** **    objects =
           ws.get_objects([{'ref':
           params['workspace_id']+'/'+params['obj_name']}]) ** ** "ref" means
           the entire name combining the workspace id and the object name **
           "id" is a numerical identifier of the workspace or object, and
           should just be used for workspace ** "name" is a string identifier
           of a workspace or object.  This is received from Narrative.),
           parameter "input_one_sequence" of type "sequence", parameter
           "input_one_name" of type "data_obj_name", parameter
           "input_many_name" of type "data_obj_name", parameter
           "input_msa_name" of type "data_obj_name", parameter
           "output_one_name" of type "data_obj_name", parameter
           "output_filtered_name" of type "data_obj_name", parameter
           "ident_thresh" of Double, parameter "e_value" of Double, parameter
           "bitscore" of Double, parameter "overlap_fraction" of Double,
           parameter "maxaccepts" of Double, parameter "rounds" of Double
        :returns: instance of type "BLAST_Output" (BLAST Output) ->
           structure: parameter "report_name" of type "data_obj_name",
           parameter "report_ref" of type "data_obj_ref"
        """
        return self._client.call_method(
            'kb_blast.BLASTx_Search',
            [params], self._service_ver, context)

    def tBLASTn_Search(self, params, context=None):
        """
        :param params: instance of type "BLAST_Params" (BLAST Input Params)
           -> structure: parameter "workspace_name" of type "workspace_name"
           (** The workspace object refs are of form: ** **    objects =
           ws.get_objects([{'ref':
           params['workspace_id']+'/'+params['obj_name']}]) ** ** "ref" means
           the entire name combining the workspace id and the object name **
           "id" is a numerical identifier of the workspace or object, and
           should just be used for workspace ** "name" is a string identifier
           of a workspace or object.  This is received from Narrative.),
           parameter "input_one_sequence" of type "sequence", parameter
           "input_one_name" of type "data_obj_name", parameter
           "input_many_name" of type "data_obj_name", parameter
           "input_msa_name" of type "data_obj_name", parameter
           "output_one_name" of type "data_obj_name", parameter
           "output_filtered_name" of type "data_obj_name", parameter
           "ident_thresh" of Double, parameter "e_value" of Double, parameter
           "bitscore" of Double, parameter "overlap_fraction" of Double,
           parameter "maxaccepts" of Double, parameter "rounds" of Double
        :returns: instance of type "BLAST_Output" (BLAST Output) ->
           structure: parameter "report_name" of type "data_obj_name",
           parameter "report_ref" of type "data_obj_ref"
        """
        return self._client.call_method(
            'kb_blast.tBLASTn_Search',
            [params], self._service_ver, context)

    def tBLASTx_Search(self, params, context=None):
        """
        :param params: instance of type "BLAST_Params" (BLAST Input Params)
           -> structure: parameter "workspace_name" of type "workspace_name"
           (** The workspace object refs are of form: ** **    objects =
           ws.get_objects([{'ref':
           params['workspace_id']+'/'+params['obj_name']}]) ** ** "ref" means
           the entire name combining the workspace id and the object name **
           "id" is a numerical identifier of the workspace or object, and
           should just be used for workspace ** "name" is a string identifier
           of a workspace or object.  This is received from Narrative.),
           parameter "input_one_sequence" of type "sequence", parameter
           "input_one_name" of type "data_obj_name", parameter
           "input_many_name" of type "data_obj_name", parameter
           "input_msa_name" of type "data_obj_name", parameter
           "output_one_name" of type "data_obj_name", parameter
           "output_filtered_name" of type "data_obj_name", parameter
           "ident_thresh" of Double, parameter "e_value" of Double, parameter
           "bitscore" of Double, parameter "overlap_fraction" of Double,
           parameter "maxaccepts" of Double, parameter "rounds" of Double
        :returns: instance of type "BLAST_Output" (BLAST Output) ->
           structure: parameter "report_name" of type "data_obj_name",
           parameter "report_ref" of type "data_obj_ref"
        """
        return self._client.call_method(
            'kb_blast.tBLASTx_Search',
            [params], self._service_ver, context)

    def psiBLAST_msa_start_Search(self, params, context=None):
        """
        :param params: instance of type "BLAST_Params" (BLAST Input Params)
           -> structure: parameter "workspace_name" of type "workspace_name"
           (** The workspace object refs are of form: ** **    objects =
           ws.get_objects([{'ref':
           params['workspace_id']+'/'+params['obj_name']}]) ** ** "ref" means
           the entire name combining the workspace id and the object name **
           "id" is a numerical identifier of the workspace or object, and
           should just be used for workspace ** "name" is a string identifier
           of a workspace or object.  This is received from Narrative.),
           parameter "input_one_sequence" of type "sequence", parameter
           "input_one_name" of type "data_obj_name", parameter
           "input_many_name" of type "data_obj_name", parameter
           "input_msa_name" of type "data_obj_name", parameter
           "output_one_name" of type "data_obj_name", parameter
           "output_filtered_name" of type "data_obj_name", parameter
           "ident_thresh" of Double, parameter "e_value" of Double, parameter
           "bitscore" of Double, parameter "overlap_fraction" of Double,
           parameter "maxaccepts" of Double, parameter "rounds" of Double
        :returns: instance of type "BLAST_Output" (BLAST Output) ->
           structure: parameter "report_name" of type "data_obj_name",
           parameter "report_ref" of type "data_obj_ref"
        """
        return self._client.call_method(
            'kb_blast.psiBLAST_msa_start_Search',
            [params], self._service_ver, context)

    def status(self, context=None):
        return self._client.call_method('kb_blast.status',
            [], self._service_ver, context)
